Fix GCC 8 warning about memcpying non-trivial class
In this case, it's easier to just make it trivial. Note how it contains
a pointer which isn't deleted in the destructor (which is why we can
make it trivial).

 glcommandqueue.cpp:181:75: error: ‘void* memcpy(void*, const void*, size_t)’ writing to an object of non-trivially copyable type ‘class
 QtCanvas3D::GlCommand’; use copy-assignment or copy-initialization instead [-Werror=class-memaccess]

Change-Id: I052407b777ec43f78378fffd15310c2121146ef2
Reviewed-by: Ville Voutilainen <ville.voutilainen@qt.io>